### ISSUE TITLE
Microstrain inertial driver update from 2.6.0 to 3.0.0 no longer allows to hit 200Hz on 3DMGX5-AHRS

### ISSUE THREAD

**Issue by pjmara** [LORD-MicroStrain/microstrain_inertial_driver_common#44] opened 2023-02-09 22:45 UTC
Fairly simple issue (I hope)
Our team had been using version 2.6.0 of the Microstrain Inertial Driver to collect imu data. Our custom config file set the imu_data_rate field to 200.
The method of measuring the actual rate is by inspecting a rosbag where we bag all of the data on the topic /imu/data, count the messages received, and divide by the length of the rosbag. 
Upon updating to version 3.0.0 (installed from apt) we cannot hit this rate using the same configuration file. We are seeing numbers in the range 150-190 now. 

Has anyone else seen rate problems after updating the driver version? 
Maintainers, please let me know what else is needed for an issue diagnosis...

**Comment by robbiefish** [comment] 2023-02-10 18:16
@pjmara, thank you for bringing this to our attention. This was a problem with how the data gets batched when using USB.

#45 should Resolve this.

As a side note, it is important to note that 200 is technically not a valid data rate for the IMU data on a GX5-AHRS. When configuring any of the `_data_rate` fields what you are really setting is the decimation we set on the sensor. Since the base data rate of the IMU data on a GX5-AHRS is 500hz, and 200hz is not evenly divisible, we can not set a decimation to acheive that data rate. As such, if you set the data rate to 200, you will actually receive the data at 250 hertz. The driver should log a warning in these cases

**Comment by pjmara** [comment] 2023-02-10 19:27
> #45 should Resolve this.
To me it seems like this PR is about fixing decimation rate and messaging surrounding decimation rate. At least that is what the PR says. Our behavior is an inconsistent data rate ranging all over the place between roughly 150-190 hz... I guess I don't see how that fix helps us? Unless you are saying we have a bad decimation rate which is giving undefined behavior

> As a side note, it is important to note that 200 is technically not a valid data rate for the IMU data on a GX5-AHRS. 
Perhaps I gave you the wrong spec? Our IMU is [this imu](https://www.microstrain.com/inertial-sensors/3dm-gx5-25) and that model number 3DMGX5-AHRS at the top of the page I assumed was a one-to-one mapping. 
The spec says that you can get raw imu measurements up to 1khz, so I thought that was our base rate? (evenly divisible, 1000/5)

**Comment by robbiefish** [comment] 2023-02-10 19:37
> To me it seems like this PR is about fixing decimation rate and messaging surrounding decimation rate. At least that is what the PR says. Our behavior is an inconsistent data rate ranging all over the place between roughly 150-190 hz... I guess I don't see how that fix helps us? Unless you are saying we have a bad decimation rate which is giving undefined behavior

I was able to recreate the behavior you were seeing. It was due to the fact that we would only publish after all data packets for a cycle were processed, but when we process a data packet, we override existing data in the message buffer. So when more than one packet arrived in a cycle which happens sometimes with high data rates, especially with USB buffering, we would override some data and only publish the most recent packet's data.

There are also some additional changes in there having to do with checking decimation and making sure we are spinning at the right rate to be able to handle data properly, apologies for the confusion.

The main fix related to this issue is that we publish [here](https://github.com/LORD-MicroStrain/microstrain_inertial_driver_common/pull/45/files#diff-4b15d42f4af5053b925f503bf95605d6255819058756248876f181f4e0edf32eR947) after every data packet, instead of [here](https://github.com/LORD-MicroStrain/microstrain_inertial_driver_common/pull/45/files#diff-94c626ad23019244b784193681f143938d018f121030431f436793c2bc0bc6b8L50) after all data packets per cycle


> Perhaps I gave you the wrong spec? Our IMU is [this imu](https://www.microstrain.com/inertial-sensors/3dm-gx5-25) and that model number 3DMGX5-AHRS at the top of the page I assumed was a one-to-one mapping.
> The spec says that you can get raw imu measurements up to 1khz, so I thought that was our base rate? (evenly divisible, 1000/5)

You gave me the right spec, it was me who looked at the wrong device, apologies for the confusion again

**Comment by robbiefish** [comment] 2023-02-10 20:37
@pjmara I could get this pushed through and released if that is the only way you are able to test this as I am fairly confident this is the fix for this particular issue, but are you able to test on this branch to verify that the issue is gone? We have documentation on building from source [here](https://github.com/LORD-MicroStrain/microstrain_inertial#source)

**Comment by pjmara** [comment] 2023-02-10 20:39
Can confirm building from source fixed! I would definitely love to get it into the version in apt at some point so that when we have new devices we can just install from apt...our current solution is building a .deb ourselves and installing it on our hardware

**Comment by robbiefish** [comment] 2023-02-10 21:34
Should be fixed in `3.0.1`

**Closed by robbiefish** 2023-02-10 21:34 UTC

**Comment by pjmara** [comment] 2023-02-10 22:09
How long (roughly) until this will be available on the apt install? Trying to figure out if fighting through these bloom-generate errors is worth my time :(

**Comment by robbiefish** [comment] 2023-02-13 16:16
There doesn't appear to be a set time for when the ROS maintainers do package syncs. The maintainers approved my PRs, so it should be available in the next sync.

If you don't want to wait for that, you could use the [TestingRepository](http://wiki.ros.org/TestingRepository) until then, which has it available right now, but comes with all the risks of the testing repository
